apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-crawler
  template:
    metadata:
      labels:
        app: web-crawler
    spec:
      containers:
      - name: web-crawler
        image: web-crawler:1.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-crawler
spec:
  selector:
    app: web-crawler
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: ClusterIP